apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-entitlement
  namespace: ibm-tas
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ibm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ .registryHost }}":{"username":"{{ .registryName }}","password":"{{ .password }}", "auth":"{{ printf "%s:%s" .registryName .password | b64enc }}"}}}'
  data:
  - secretKey: registryName
    remoteRef:
      key: kv/test
      property: 'docker-username'
  - secretKey: registryHost
    remoteRef:
      key: kv/test
      property: 'docker-server'
  - secretKey: password
    remoteRef:
      key: kv/test
      property: 'docker-password'
