apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: tas-operator-group
  namespace: ibm-tas
spec:
  targetNamespaces:
    - ibm-tas
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tririga
  namespace: ibm-tas
spec:
  channel: v11.5
  installPlanApproval: Automatic
  name: tririga
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-tririga.v11.5.0
