apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-key-pair
  namespace: mongodb
spec:
  secretStoreRef:
    name: ibm-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: tls.crt
      remoteRef:
        key: imported_cert/mongodb-ca-key-pair
        property: certificate
    - secretKey: tls.key
      remoteRef:
        key: imported_cert/mongodb-ca-key-pair
        property: private_key
