apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-configmap-cluster-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-configmap-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: ibm-sls-operator
  namespace: ibm-sls
roleRef:
  kind: ClusterRole
  name: read-configmap-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: crd-creator-pod
  namespace: ibm-sls
spec:
  serviceAccountName: ibm-sls-operator
  containers:
  - name: crd-creator-container
    image: openshift/origin-cli:latest
    command:
    - "/bin/sh"
    - "-c"
    - |
      MONGO_CRT=$(oc get configmap custom-ca -n mongodb -o jsonpath='{.data.ca\.crt}')
      oc create -f - <<< '{"apiVersion":"sls.ibm.com/v1","kind":"LicenseService","metadata":{"name":"sls","namespace":"ibm-sls"},"spec":{"license":{"accept":true},"mongo":{"configDb":"admin","nodes":[{"host":"my-mongodb-0.my-mongodb-svc.mongodb.svc.cluster.local","port":27017},{"host":"my-mongodb-1.my-mongodb-svc.mongodb.svc.cluster.local","port":27017},{"host":"my-mongodb-2.my-mongodb-svc.mongodb.svc.cluster.local","port":27017}],"retryWrites":true,"secretName":"sls-mongo-credentials","certificates":[{"alias":"mongoca","crt":"{{MONGO_CRT}}"}]},"rlks":{"storage":{"class":"ocs-storagecluster-cephfs","size":"5G"}},"settings":{"auth":{"enforce":false},"compliance":{"enforce":false},"reconciliation":{"enabled":true,"reconciliationPeriod":1800},"registration":{"open":true},"reporting":{"maxDailyReports":90,"maxHourlyReports":24,"maxMonthlyReports":12,"reportGenerationPeriod":3600,"samplingPeriod":900}}}}'
