# 4 - create IBM Entitlement secret - note must make changes
apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement
  namespace: ibm-common-services
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config-json>