apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibmcloud-secrets-manager-example
spec:
  secretStoreRef:
    name: ibmcloud-secrets-manager-example
    kind: SecretStore
  target:
    name: ibmcloud-secrets-manager-example
  data:
  - secretKey: username
    remoteRef:
      property: username
      key: username_password/<SECRET_ID>
  - secretKey: password
    remoteRef:
      property: password
      key: username_password/<SECRET_ID>
