kind: ClusterSecretStore
apiVersion: external-secrets.io/v1beta1
metadata:
  name: ibm-cluster-secret-store
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            key: apiKey
            name: ibm-secret
            namespace: default
      serviceUrl: https://8a7c253e-fa7f-44fc-9f3a-509678d16845.eu-de.secrets-manager.appdomain.cloud
