kind: ClusterSecretStore
apiVersion: external-secrets.io/v1beta1
metadata:
  name: ibm-cluster-secret-store
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            key: apiKey
            name: ibm-secret
            namespace: default
      serviceUrl: https://7aaf16e2-7b7e-4184-9483-1dc618609141.eu-de.secrets-manager.appdomain.cloud
