apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ibmcloud-secrets-manager-example
spec:
  provider:
    ibm:
      serviceUrl: <endpoint_url>
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: secret-api-key
            key: apikey
